### ISSUE TITLE
What is PID assist2009_pid

### ISSUE THREAD

**Issue by jaideep11061982** [arghosh/AKT#2]
Could u help understand this parameter a bit thanks

**Comment by arghosh** [comment]
assist2009 and assist2017 contains concept ids (n_question) and question ids (n_pid). For these two datasets, I named the datasets with pid. In general, you can run model akt_cid (will not use n_pid) or akt_pid (use n_pid). For other datasets, no question ids are available. So you can run only akt_cid.
