### ISSUE TITLE
why in test() function. The qa_data pass into model? 

### ISSUE THREAD

**Issue by phanxuanphucnd** [arghosh/AKT#3]
why in test() function. The all qa_data pass into model?  That is, the *i'th* response passed into model to predict for the *i'th* response? 

![1](https://user-images.githubusercontent.com/32262730/103885778-1a282880-5113-11eb-97f3-4daa8d5a55b3.png)

**Comment by phanxuanphucnd** [comment]
hi @arghosh pls, help me !

**Comment by arghosh** [comment]
Hi @phanxuanphucnd,  it is passed to check the accuracy of the model. If you see the forward pass of the model, it will use 1:t-1 responses to predict t^th response. This is done via mask in the model.

**Comment by phanxuanphucnd** [comment]
Hi @arghosh. 
In my understanding, this seems to be true as we already know the labels of tests. Assume that, labels is unavailable. How does this work?

**Comment by arghosh** [comment]
So in KT framework, we predict future responses based on past performances. If the prior history is 0, the model will be bad. Suppose, you want to predict t^th response (which is unavailable) based on t-1 responses (these should be available), just put anything (0, or 1) for the t^th response.

I am assuming you are talking about challenge setup. I need to understand what your exact problem setup is. Depending on your problem, it might not be a KT problem. You can use some collaborative filtering based techniques.

**Comment by phanxuanphucnd** [comment]
Yes, Thanks @arghosh !

**Comment by aporia3517** [comment]
Hi @arghosh, First of all, thank you for sharing your great work.

I'm wondering which part of the source code is masking or slicing the responses (targets) to allow the model to use (1:t-1) responses for predicting t^th response: (p(r_t | q_{1 : t-1}, r_{1: t-1}).

**Comment by arghosh** [comment]
in akt.py code Line 159 => Line 208 =>Line 281 =>Line 326 it masks the current and future responses.
