### ISSUE TITLE
Masking or slicing allowing the model to use previous interactions

### ISSUE THREAD

**Issue by aporia3517** [arghosh/AKT#7]
Hi @arghosh, First of all, thank you for sharing your great work.

Regarding #3, I'm wondering which part of the source code is masking or slicing the responses (targets).

That is, the part to allow the model to use (1:t-1) responses for predicting t^th response: p(r_t | q_{1 : t-1}, r_{1: t-1}).

**Comment by arghosh** [comment]
in akt.py code Line 159 => Line 208 =>Line 281 =>Line 326 it masks the current and future responses.
when mask=0 in L159, src_mask in L208 is upper triangular. And lower triangular (masking the current step) in line 324

**Comment by aporia3517** [comment]
Thanks for the reply

**Comment by ghzha0** [comment]
Hi @arghosh, Thank you for your sharing!

I have a confusion in your masking.

In akt.py code Line 328

<img width="602" alt="image" src="https://user-images.githubusercontent.com/51900582/181770761-f584a211-c985-47de-9603-bead4b783185.png">

In this line, these cat option only switch the first row of masking matrice with zeropadding, while other row stay the same. 

Would it be like this?
<img width="590" alt="image" src="https://user-images.githubusercontent.com/51900582/181772832-73588a67-dd6e-45e4-86d6-8fc84c03cae3.png">

**Comment by lif323** [comment]
> Hi @arghosh, Thank you for your sharing!
> 
> I have a confusion in your masking.
> 
> In akt.py code Line 328
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/51900582/181770761-f584a211-c985-47de-9603-bead4b783185.png">
> 
> In this line, these cat option only switch the first row of masking matrice with zeropadding, while other row stay the same.
> 
> Would it be like this? <img alt="image" width="590" src="https://user-images.githubusercontent.com/51900582/181772832-73588a67-dd6e-45e4-86d6-8fc84c03cae3.png">

I think it set the first row to all zeros instead of the first column of scores. Prior to the operations, the first row of scores is initialized with small values(-1e32). Although they remain as small values after softmax, they are not zeros. Therefore, this operation is essential.
